apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventure-project-gh-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventure-project-gh
  template:
    metadata:
      labels:
        app: eventure-project-gh
    spec:
      containers:
        - name: eventure-project-gh
          image: eventure-GH   
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
